### ISSUE TITLE
Not all connection errors properly caught

### ISSUE THREAD

**Issue by stephenplaza** [janelia-flyem/dvidjs#1]
When I try to connect to an erroneous DVID server or port, the errors generally get caught.  However, when I try to find a DVID server with a port number beyond the max range, I get the following:

Uncaught Error: NETWORK_ERR: XMLHttpRequest Exception 101

This is not a big deal because I can check the port range before requesting but this should probably be handled by the library in a more graceful fashion.

**Comment by neomorphic** [comment]
What version of the API were you using and what browser?

**Comment by stephenplaza** [comment]
Should have been the latest at the time: 0.21.

Chrome

**Comment by neomorphic** [comment]
Fixed in b1893ba
